import { getAddress } from "viem";
import { STOCK_TOKEN_ALLOWLISTS } from "./robinhood-stock-tokens.js";
import type { StockNetworkId, StockTokenListing } from "./stock-tokens.js";

/**
 * Global Dollar (USDG), the dollar stablecoin on Robinhood Chain's official contracts page
 * (https://docs.robinhood.com/chain/contracts/). Read back from chain 4663 on 2026-09-30: deployed bytecode (a Paxos
 * EIP-1967 proxy), decimals() == 6, symbol() == "USDG", name() == "Global Dollar". The issuer can pause transfers
 * and freeze addresses. Robinhood publishes no testnet deployment, so USDG is a mainnet asset only.
 */
export const ROBINHOOD_USDG: StockTokenListing = {
  symbol: "USDG",
  name: "Global Dollar",
  kind: "cash",
  address: "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
  decimals: 6,
};
export const ROBINHOOD_USDG_VERIFIED_ON = "2026-09-30";

/**
 * Every token HaPaPay moves on a Robinhood network: USDG on mainnet, then the verified Stock Tokens. The Stock Token part stays generated by `npm run sync:stock-tokens`; nothing here is live data.
 */
export const ROBINHOOD_ASSET_ALLOWLISTS: Record<StockNetworkId, { tokens: readonly StockTokenListing[]; verifiedOn: string }> = {
  "robinhood-mainnet": {
    tokens: [ROBINHOOD_USDG, ...STOCK_TOKEN_ALLOWLISTS["robinhood-mainnet"].tokens],
    verifiedOn: STOCK_TOKEN_ALLOWLISTS["robinhood-mainnet"].verifiedOn,
  },
  "robinhood-testnet": STOCK_TOKEN_ALLOWLISTS["robinhood-testnet"],
};

/** The allowlisted token at this address on this network, if any. */
export function robinhoodAsset(network: StockNetworkId, address: string) {
  let token: string;
  try {
    token = getAddress(address);
  } catch {
    return undefined;
  }
  return ROBINHOOD_ASSET_ALLOWLISTS[network].tokens.find((entry) => entry.address === token);
}

/** The allowlist entry for this exact ticker and address on this network, if there is one. */
export function allowlistedRobinhoodAsset(network: StockNetworkId, input: { symbol: string; address: string }) {
  const token = robinhoodAsset(network, input.address);
  return token && token.symbol === input.symbol ? token : undefined;
}

/** Tickers listed on any Robinhood network, so a ticker from the other network is explained instead of guessed. */
export const KNOWN_ROBINHOOD_SYMBOLS: ReadonlySet<string> = new Set(
  [...Object.values(ROBINHOOD_ASSET_ALLOWLISTS).flatMap(({ tokens }) => tokens.map((token) => token.symbol)), ROBINHOOD_USDG.symbol],
);
