import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import solc from "solc";
import { keccak256, stringToHex, type Abi, type Hex } from "viem";

/**
 * The contracts the operator page deploys from the operator's wallet: on Robinhood Chain the vault escrow, the fee
 * router and the burn vault; on Arc the same escrow and router, the fee forwarder in place of the burn vault, and the
 * identity registry.
 */
export const OPERATOR_CONTRACT_SOURCES = {
  StockClaimEscrow: "contracts/StockClaimEscrow.sol",
  HaPaPayRouter: "contracts/HaPaPayRouter.sol",
  HaPaPayBurnVault: "contracts/HaPaPayBurnVault.sol",
  HaPaPayFeeForwarder: "contracts/HaPaPayFeeForwarder.sol",
  ArcIdentityRegistry: "contracts/ArcIdentityRegistry.sol",
} as const;

export type OperatorContractName = keyof typeof OPERATOR_CONTRACT_SOURCES;

export const STOCK_CLAIM_ESCROW_SOURCE_PATH = OPERATOR_CONTRACT_SOURCES.StockClaimEscrow;

type CompilerOutput = {
  errors?: Array<{ severity: string; formattedMessage: string }>;
  contracts: Record<string, Record<string, { abi: Abi; evm: { bytecode: { object: string }; deployedBytecode: { object: string } } }>>;
};

/** Standard JSON input for one deployed contract; the same input verifies the source on an explorer. */
export function operatorContractCompilerInput(path: string, source: string) {
  return {
    language: "Solidity",
    sources: { [path]: { content: source } },
    settings: {
      optimizer: { enabled: true, runs: 200 },
      evmVersion: "cancun",
      outputSelection: { "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object"] } },
    },
  };
}

export function stockClaimEscrowCompilerInput(source: string) {
  return operatorContractCompilerInput(STOCK_CLAIM_ESCROW_SOURCE_PATH, source);
}

export async function compileOperatorContract(name: OperatorContractName) {
  const path = OPERATOR_CONTRACT_SOURCES[name];
  const source = await readFile(new URL(`../${path}`, import.meta.url), "utf8");
  const output = JSON.parse(solc.compile(JSON.stringify(operatorContractCompilerInput(path, source)))) as CompilerOutput;
  const diagnostics = (output.errors ?? []).filter((entry) => entry.severity === "error" || entry.severity === "warning");
  if (diagnostics.length) throw new Error(diagnostics.map((entry) => entry.formattedMessage).join("\n"));
  const contract = output.contracts[path][name];
  const deployedBytecode = `0x${contract.evm.deployedBytecode.object}` as Hex;
  return {
    abi: contract.abi,
    compiler: solc.version(),
    sourceHash: keccak256(stringToHex(source)),
    runtimeCodeHash: keccak256(deployedBytecode),
    bytecode: `0x${contract.evm.bytecode.object}` as Hex,
    deployedBytecode,
  };
}

export function compileStockClaimEscrow() {
  return compileOperatorContract("StockClaimEscrow");
}

type Compiled = Awaited<ReturnType<typeof compileOperatorContract>>;

const artifactObject = (name: string, compiled: Compiled) => `{
  contractName: "${name}",
  compiler: "${compiled.compiler}",
  sourceHash: "${compiled.sourceHash}",
  runtimeCodeHash: "${compiled.runtimeCodeHash}",
  bytecode: "${compiled.bytecode}",
} as const`;

export function renderStockClaimEscrowArtifact(compiled: Compiled) {
  return `// Generated by \`npm run generate:stock-escrow\` from ${STOCK_CLAIM_ESCROW_SOURCE_PATH}. Do not edit by hand.
// The operator page deploys this creation bytecode, and the server registers an escrow only when the deployed
// runtime code hashes to runtimeCodeHash. solc ${compiled.compiler}, optimizer 200 runs, EVM cancun.
export const STOCK_CLAIM_ESCROW_ARTIFACT = ${artifactObject("StockClaimEscrow", compiled)};
`;
}

export function renderFeeArtifacts(router: Compiled, vault: Compiled, forwarder: Compiled) {
  return `// Generated by \`npm run generate:stock-escrow\` from ${OPERATOR_CONTRACT_SOURCES.HaPaPayRouter},
// ${OPERATOR_CONTRACT_SOURCES.HaPaPayBurnVault} and ${OPERATOR_CONTRACT_SOURCES.HaPaPayFeeForwarder}. Do not edit by hand. The operator
// page deploys this creation bytecode, and the server accepts the fee contracts behind an escrow only when their runtime
// code hashes to runtimeCodeHash. solc ${router.compiler}, optimizer 200 runs, EVM cancun.
export const PAY_ROUTER_ARTIFACT = ${artifactObject("HaPaPayRouter", router)};

export const BURN_VAULT_ARTIFACT = ${artifactObject("HaPaPayBurnVault", vault)};

export const FEE_FORWARDER_ARTIFACT = ${artifactObject("HaPaPayFeeForwarder", forwarder)};
`;
}

export function renderArcIdentityRegistryArtifact(compiled: Compiled) {
  return `// Generated by \`npm run generate:stock-escrow\` from ${OPERATOR_CONTRACT_SOURCES.ArcIdentityRegistry}. Do not edit by hand.
// The operator page deploys this creation bytecode on Arc, and the server accepts a registry only when its runtime code
// hashes to runtimeCodeHash. solc ${compiled.compiler}, optimizer 200 runs, EVM cancun.
export const ARC_IDENTITY_REGISTRY_ARTIFACT = ${artifactObject("ArcIdentityRegistry", compiled)};
`;
}

async function main() {
  const [escrow, router, vault, forwarder, registry] = await Promise.all([
    compileStockClaimEscrow(),
    compileOperatorContract("HaPaPayRouter"),
    compileOperatorContract("HaPaPayBurnVault"),
    compileOperatorContract("HaPaPayFeeForwarder"),
    compileOperatorContract("ArcIdentityRegistry"),
  ]);
  await writeFile(fileURLToPath(new URL("../src/domain/stock-claim-escrow-artifact.ts", import.meta.url)), renderStockClaimEscrowArtifact(escrow));
  await writeFile(fileURLToPath(new URL("../src/domain/fee-artifacts.ts", import.meta.url)), renderFeeArtifacts(router, vault, forwarder));
  await writeFile(fileURLToPath(new URL("../src/domain/arc-identity-registry-artifact.ts", import.meta.url)), renderArcIdentityRegistryArtifact(registry));
  for (const [name, compiled] of [["StockClaimEscrow", escrow], ["HaPaPayRouter", router], ["HaPaPayBurnVault", vault], ["HaPaPayFeeForwarder", forwarder], ["ArcIdentityRegistry", registry]] as const) {
    console.log(`${name}: ${(compiled.bytecode.length - 2) / 2} bytes of creation code, runtime ${compiled.runtimeCodeHash}.`);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
